### PR TITLE
Add airflow_dag_last_status_time to help find last dag status.

### PR DESCRIPTION
**Pull request by andreyev**
Then we can do `airflow_dag_last_status_time{status="failed"} - airflow_dag_last_status_time{status="success"} > 0` to catch current failures.

This can be related to issue #43 .

### CODE REVIEW

**Comment by elephantum** [comment]
@andreyev thanks for PR!

What if failed or success statuses never occurred for a specific DAG?

Hypotheses: Maybe it'll be more straight forward to add `airflow_dag_last_status{status="xxx"} = 0/1` ?

**Comment by andreyev** [comment]
> @andreyev thanks for PR!

I thank you for all you all have done here! ;-)

> What if failed or success statuses never occurred for a specific DAG?

Then `airflow_dag_last_status_time` is not shown for this DAG/status...

> Hypotheses: Maybe it'll be more straight forward to add `airflow_dag_last_status{status="xxx"} = 0/1` ?

It would be better, I agree, I thought about doing it first, but I cant do this without change a lot of things and I dont know python/airflow so well to do this... :-(

PS: I guess that there is a plus about this "time-based approach" that is it make easy to know when the last failure/success happened, i.e. "More than X days since last failure" ;-)

**Comment by panovst** [comment]
Hello! 
Is there any progress on this PR?
I now need to determine the latest status of the DAG in the project

**Comment by elephantum** [comment]
Fixed by #96

**Pull request closed without merging**
