### PR TITLE
Deliver plugin as a python package

### LINKED ISSUE #44: Deliver plugin as a python package
Airflow has the ability to load plugins as python packages.

I'd be happy to contribute a setup.py and do release management to pypi if you are interested.

Alternatively, if you are not interested in doing that out of this repo I can set up a fork with the necessary setup.py release management tooling.

See https://airflow.apache.org/plugins.html#plugins-as-python-packages for some info.

### PR DESCRIPTION
**Pull request by maxbrunet**
* Add `setup.py` and related files
* Move Python module under `airflow_exporter` package
* Add (commented out) deployment to PyPI via Travis CI
* Update installation instruction in `README.md`

I chose `airflow-exporter`/`airflow_exporter` as package name, but it's open to change.
The tests should also be updated to use an installed package (`pip install -e .` for development and `pip install .` for CI tests).

Thank you for this nice plugin.

Closes #44

### CODE REVIEW

**Comment by elephantum** [comment]
@maxbrunet great job! We'll test it shortly

**Comment by elephantum** [comment]
@maxbrunet do I understand correctly, that Travis tests do not use this distribution by package?

**Comment by maxbrunet** [comment]
> @maxbrunet do I understand correctly, that Travis tests do not use this distribution by package?

Yes, I'll work on that if I have time, else I'll leave it to you

**Comment by maxbrunet** [comment]
Hi @elephantum, I just pushed the updated tests, I took the liberty to do a lot of refactoring. A few things about it:
* It only tests Airflow 1.10.3, since it's the only supported version (for now)
* It uses the `matrix` feature to easily test more versions (everything should be configurable via environment variables)
* The tests environment is self-contained in `docker-compose.test.yml`
* I added a `docker-compose.yml` for development. There, it doesn't really install the package, but mounts the module directly in the user's site-packages (I haven't been able to make `pip install --editable` work inside the container while mounting the local directory)
* I initiated a `CONTRIBUTING.md` file to document how to run the dev and test environments
* The `AIRFLOW__WEBSERVER__RBAC` environment variable is passed to tests container, if ever you need to check if RBAC is enabled or not from there

Hope you'll like this new setup.

**Comment by elephantum** [comment]
@maxbrunet Incredible job! I like your approach it's very elegant and clean.

**Pull request merged**
