### PR TITLE
fetch DAG stats from DagRun instead of DagStat

### PR DESCRIPTION
**Pull request by sockeye44**
fix for #46

### CODE REVIEW

**Comment by elephantum** [comment]
@sockeye44 thanks for the PR!

Question: do I understand correctly that this change breaks compatibility with Airflow versions before 1.10.3?

**Comment by sockeye44** [comment]
As I understand it, it can break compatibility with some of the oldest versions, but the underlying tables/fields have been added years ago: 

- Migration for dag_run table, creation date: 2015-10-27 (https://github.com/apache/airflow/blob/master/airflow/migrations/versions/1b38cef5b76e_add_dagrun.py)
- Migration for dag table, creation date: 2015-08-18 (https://github.com/apache/airflow/blob/master/airflow/migrations/versions/e3a246e0dc1_current_schema.py)

**Comment by elephantum** [comment]
Yes, this change breaks compatibility in a silent way: it does not crash, but returns no metrics on 1.10.0.

Let's discuss what can be done about that.

Maybe we can create special branch that supports 1.10.3(rc2)+ and leave current version with note of incompatibility with 1.10.3

**Comment by elephantum** [comment]
I will merge this PR into separate branch `airflow-1.10.3` for now.

When 1.10.3 gets released, we will drop compatibility with previous versions and make a new release of airflow-exporter.

**Pull request merged**
