### PR TITLE
Fix custom labels from params

### PR DESCRIPTION
**Pull request by Brightside56**
This PR is to fix custom labels from dag parameters

### CODE REVIEW

**Comment by elephantum** [comment]
@Brightside56 can you explain, please?

Does it mean that custom labels are currently broken?

**Comment by Brightside56** [comment]
> @Brightside56 can you explain, please?
> 
> Does it mean that custom labels are currently broken?

Yes, they're not working (you can take a look on docker-compose tests to check). This PR will fix them

**Comment by Brightside56** [comment]
@elephantum how about fix? Or should I use fork instead?

**Comment by elephantum** [comment]
@Brightside56 I dug deeper into this issue, proper fix will be released with #83

**Comment by elephantum** [comment]
Fixed in version 1.4.2

**Pull request closed without merging**
