### PR TITLE
Fix for duplicated help entries

### PR DESCRIPTION
**Pull request by elephantum**

### CODE REVIEW

**Comment by elephantum** [comment]
@dusty73 @dskarataev can you please check if this attempt works for you?

I tried to preserve custom dag labels while fixing duplicate HELP entries.

**Comment by Mordowski** [comment]
The duplicate help entries issue is causing issues with our infrastructure. When can we see this merged into master?

**Comment by elephantum** [comment]
@Mordowski will merge it and release next week

**Comment by Mordowski** [comment]
> @Mordowski will merge it and release next week

@elephantum - kindly asking it there's an ETA for the merge and release.

**Pull request merged**
