### PR TITLE
Add airflow_dag_last_status

### PR DESCRIPTION
**Pull request by nvn01234**
Related to [PR69](https://github.com/epoch8/airflow-exporter/pull/69), follow the comment of @elephantum

### CODE REVIEW

**Comment by nvn01234** [comment]
> Hypotheses: Maybe it'll be more straight forward to add airflow_dag_last_status{status="xxx"} = 0/1 ?

What about if we add airflow_last_dagrun_status(...) = -1/0/1 

- -1 for failed
- 0 for running
- 1 for success

**Comment by elephantum** [comment]
@nvn01234 I updated your PR to the latest version of code, can you please check that everything works?

**Comment by nvn01234** [comment]
Nice, it worked. Result look like this:

image

I also consider to add airflow_last_dagrun_task_status (tasks's status of the last dagrun for each dag), will submit another PR later.

**Comment by elephantum** [comment]
I renamed metric for consistency.

**Comment by nvn01234** [comment]
I changed the PR title too

**Pull request merged**
